### PR TITLE
basic puffin profiler

### PR DESCRIPTION
**Pull request by CatCode79**
This is a basic implementation of the puffin profiler.

It's pretty nice, but it's not a profiler that can generate a complete flamegraph (unless you disseminate the puffin::profile_function!() macro everywhere) but useful nonetheless.

I preferred to implement it with http protocol to avoid having to integrate egui (so we will be free to choose the GUI we would like).

To connect to the profiler during the game use this:
https://github.com/EmbarkStudios/puffin/tree/main/puffin_viewer

To enable/disable the profiler the line to be modified is this: puffin::set_scopes_on(true).

There is also this macro that identifies where the frame ends (I hope I put it in the correct place): puffin::GlobalProfiler::lock().new_frame();

### CODE REVIEW

**Comment by Davidster** [comment]
awesome! taking a look at this today

**Comment by CatCode79** [comment]
Just yesterday the new version of tracy_full came out, case that I had missed as usable but potentially more interesting than Puffin because it has support for WGPU:
https://github.com/SparkyPotato/tracy_full

I think for now we can use Puffin anyway, since the changes are very easy to refactor and don't mess the code.
If we see that the puffin is not enough to profile the wgpu part maybe we will evaluate whether to use it.

**Comment by Davidster** [comment]
yes let's definitely try puffin and see how we like it. gunna check out tracy, wgpu support sounds very cool. I've been using `cargo flamegraph` so far and it's good for profiling cpu but doesn't tell you much on the gpu side

**Comment by Davidster** [comment]
Looks awesome! gunna merge it in. I like how I can press 'M' while the game is running and instantly see the render function time shrink, it's super cool. It would've helped me track down some of these perf issues more quickly, like 'get all bone data' taking 6ms, wayyyy too slow.

image

**Pull request merged**
